"""Restore raw_script and parsed_json for original chat logic

Revision ID: 535b71f5356d
Revises: 662f65d8700a
Create Date: 2025-06-20 22:48:39.679959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535b71f5356d'
down_revision = '662f65d8700a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_script', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('parsed_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.drop_column('content_html')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_html', sa.TEXT(), nullable=True))
        batch_op.drop_column('parsed_json')
        batch_op.drop_column('raw_script')

    # ### end Alembic commands ###
