"""Add completed_at timestamp to Enrollment

Revision ID: 585dfd4952ef
Revises: 94147795fa90
Create Date: 2025-06-20 10:28:20.543358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585dfd4952ef'
down_revision = '94147795fa90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
