"""Replace ContentBlock with a single HTML field in Lesson

Revision ID: 662f65d8700a
Revises: 7035d6a36b70
Create Date: 2025-06-20 20:16:01.221762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662f65d8700a'
down_revision = '7035d6a36b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_block')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('content_html')

    op.create_table('content_block',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lesson_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('block_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
