"""Add chunk index to chat history

Revision ID: 6ea0b8c16e7d
Revises: fa8097170646
Create Date: 2025-06-22 15:14:16.787073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea0b8c16e7d'
down_revision = 'fa8097170646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_chunk_index', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_column('current_chunk_index')

    # ### end Alembic commands ###
