"""Implement block-based editor models

Revision ID: 7035d6a36b70
Revises: d16a2e4997e8
Create Date: 2025-06-20 12:35:37.456178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7035d6a36b70'
down_revision = 'd16a2e4997e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('block_type', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('parsed_json')
        batch_op.drop_column('raw_script')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_script', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('parsed_json', sa.TEXT(), nullable=False))

    op.drop_table('content_block')
    # ### end Alembic commands ###
