"""Add enrollment and progress tracking table

Revision ID: 94147795fa90
Revises: dcdc362a18a4
Create Date: 2025-06-20 09:33:13.079762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94147795fa90'
down_revision = 'dcdc362a18a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('last_completed_chapter_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='_user_course_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment')
    # ### end Alembic commands ###
